# Generated by Django 4.2.28 on 2026-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_overviews', '0029_alter_historicalcourseoverview_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseoverview',
            name='variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourseoverview',
            name='variant_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
