# Generated by Django 4.2.24 on 2026-08-10 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import opaque_keys.edx.django.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('support', '0006_alter_historicalusersocialauth_extra_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUnenrollBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('csv_filename', models.CharField(blank=True, default='', max_length=255)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(choices=[('validated', 'Validated'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='validated', max_length=20)),
                ('total_courses', models.PositiveIntegerField(default=0)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BulkUnenrollCourseState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('course_id', opaque_keys.edx.django.models.CourseKeyField(db_index=True, max_length=255)),
                ('active_count', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error', models.CharField(blank=True, default='', max_length=255)),
                ('total_enrollments', models.PositiveIntegerField(default=0)),
                ('unenrolled', models.PositiveIntegerField(default=0)),
                ('already_inactive', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('chunks_total', models.PositiveIntegerField(default=0)),
                ('chunks_finished', models.PositiveIntegerField(default=0)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('started', models.DateTimeField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='support.bulkunenrollbatch')),
            ],
            options={
                'unique_together': {('batch', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='BulkUnenrollChunk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('chunk_index', models.PositiveIntegerField()),
                ('continuation', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('finished', 'Finished')], default='pending', max_length=20)),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('course_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='support.bulkunenrollcoursestate')),
            ],
            options={
                'unique_together': {('course_state', 'attempt', 'chunk_index', 'continuation')},
            },
        ),
    ]
